In [1]:
import numpy as np
def multiply(v, w):
    if len(v.shape) !=1 and len(w.shape) !=1: 
        for i,z in zip(range(len(v)),range(len(w))):
            print(v[i]*w)
    
    else:
        return v * w

In [2]:
a = np.array([[1,2,3,4],[5,6,7,8],[5,6,7,8]])
b = np.array([5,6,7,8])

In [3]:
len(b.shape)

1

In [4]:
multiply(a,b)

array([[ 5, 12, 21, 32],
       [25, 36, 49, 64],
       [25, 36, 49, 64]])

In [5]:
np.multiply(a,b)

array([[ 5, 12, 21, 32],
       [25, 36, 49, 64],
       [25, 36, 49, 64]])

In [6]:
np.matmul(a,b)

array([ 70, 174, 174])

In [7]:
def matmul(v,w):
    if len(v.shape) !=1 and len(w.shape) == 1:
        for i,z in zip(range(len(v)),range(len(w))):
            print(sum(v[i]*w))
    else:
        return sum(v * w)
    

In [8]:
matmul(a,b)

70
174
174
